version: '3'
services:

  redis-node-0:
    image: redis:alpine
    container_name: redis-cluster
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
      - '8003:8003'
      - '8004:8004'
      - '8005:8005'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-cluster/8000/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-1:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:redis-node-0"
    volumes:
      - ./redis-cluster/8001/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-2:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:redis-node-0"
    volumes:
      - ./redis-cluster/8002/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-3:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:redis-node-0"
    volumes:
      - ./redis-cluster/8003/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-4:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:redis-node-0"
    volumes:
      - ./redis-cluster/8004/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-5:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    network_mode: "service:redis-node-0"
    volumes:
      - ./redis-cluster/8005/redis.conf:/usr/local/etc/redis/redis.conf