spring:
#  autoconfigure.exclude:
#    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
#    - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  redis:
    cluster:
      nodes:
        - 0.0.0.0:8000
        - 0.0.0.0:8001
        - 0.0.0.0:8002
        - 0.0.0.0:8003
        - 0.0.0.0:8004
        - 0.0.0.0:8005
#      max-redirects: 3
    password: myredis
    lettuce:
      pool:
        enabled: true
        max-idle: 16
        max-active: 32
        min-idle: 8